wip: trying to get this script to work... dangit

diff --git a/run_onchange_00-setup-arch.sh.tmpl b/run_onchange_00-setup-arch.sh.tmpl
--- a/run_onchange_00-setup-arch.sh.tmpl
+++ b/run_onchange_00-setup-arch.sh.tmpl
@@ -1,8 +1,27 @@
 {{- if eq .chezmoi.os "linux" -}}
-{{- if eq .chezmoi.osRelease.id "arch" -}}
 #!/usr/bin/env bash
 
-echo "I ran"
+set -euo pipefail
+#IFS=$'\n\t'
+# trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+
+{{- if eq .chezmoi.osRelease.id "arch" -}}
+
+function appInstall {
+  
+  if [[ $# -lt 1 ]]; then
+    echo "Invalid appInstall argument is missing"
+    return 1
+  fi
+
+  local app="$1"
+
+  if ! command -v $app >/dev/null 2>&1; then
+    yay -Sy $app
+  fi
+}
 
 {{- end -}}
+
+appInstall evolution
 {{- end -}}
